language: node_js
node_js:
  - 14

services:
  - docker

script:
  - docker --version # print the version for logging
## Build
  - docker build -t lexflex/udagram-api-feed:latest -f ./udagram-api-feed/Dockerfile ./udagram-api-feed
  - docker build -t lexflex/udagram-api-user:latest -f ./udagram-api-user/Dockerfile ./udagram-api-user
  - docker build -t lexflex/udagram-frontend:latest -f ./udagram-frontend/Dockerfile ./udagram-frontend
  - docker build -t lexflex/reverseproxy:latest -f ./udagram-reverseproxy/Dockerfile ./udagram-reverseproxy

after_success:
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lexflex/udagram-api-feed:latest
  - docker push lexflex/udagram-api-user:latest
  - docker push lexflex/udagram-frontend:latest
  - docker push lexflex/reverseproxy:latest
