## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands+

## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-frontend
  - docker build -t udagram-api-feed ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed lexflex/udagram-api-feed:v1
  - docker tag udagram-api-feed lexflex/udagram-api-user:v1
  - docker tag udagram-api-feed lexflex/udagram-api-frontend:v1
  - docker tag udagram-api-feed lexflex/udagram-api-reverseproxy:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lexflex/udagram-api-feed:v1
  - docker push lexflex/udagram-api-user:v1
  - docker push lexflex/udagram-api-frontend:v1
  - docker push lexflex/udagram-api-reverseproxy:v1
## Do similar for other three images