language: node_js
node_js:
  - 14

services:
  - docker

script:
  - docker --version # print the version for logging
## Build
  - docker build -t lexflex/udagram-api-feed:latest udagram-api-feed -f ./udagram-api-feed/Dockerfile ./udagram-api-feed
  - docker build -t lexflex/udagram-api-user:latest udagram-api-user -f ./udagram-api-user/Dockerfile ./udagram-api-user
  - docker build -t lexflex/udagram-api-frontend:latest udagram-api-frontend -f ./udagram-api-frontend/Dockerfile ./udagram-api-frontend
  - docker build -t lexflex/udagram-api-reverseproxy:latest udagram-api-reverseproxy -f ./udagram-reverseproxy/Dockerfile ./udagram-reverseproxy

after_success:
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lexflex/udagram-api-feed:latest
  - docker push lexflex/udagram-api-user:latest
  - docker push lexflex/udagram-api-frontend:latest
  - docker push lexflex/udagram-api-reverseproxy:latest
